# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateUSC <- function(U, U0, lam, gam, max_iter, precision_thres, V, Type, Pa, WV, WE, C) {
    .Call('_tgcc_updateUSC', PACKAGE = 'tgcc', U, U0, lam, gam, max_iter, precision_thres, V, Type, Pa, WV, WE, C)
}

updateUBC <- function(U, U0, lam, gam, max_iter, precision_thres, V_s, Type_s, Pa_s, WV_s, WE_s, C_s, V_f, Type_f, Pa_f, WV_f, WE_f, C_f) {
    .Call('_tgcc_updateUBC', PACKAGE = 'tgcc', U, U0, lam, gam, max_iter, precision_thres, V_s, Type_s, Pa_s, WV_s, WE_s, C_s, V_f, Type_f, Pa_f, WV_f, WE_f, C_f)
}

init_prepare <- function(from, to, dist, gamma) {
    .Call('_tgcc_init_prepare', PACKAGE = 'tgcc', from, to, dist, gamma)
}

updatenew <- function(Theta, input, V, T, P, WV, WE, C) {
    .Call('_tgcc_updatenew', PACKAGE = 'tgcc', Theta, input, V, T, P, WV, WE, C)
}

dp <- function(x, lam, Vertice, Type, Parent, WeightV, WeightE, Children) {
    .Call('_tgcc_dp', PACKAGE = 'tgcc', x, lam, Vertice, Type, Parent, WeightV, WeightE, Children)
}

