# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateUSC <- function(dataMatrix, initialMatrix, lambda, gamma, maxIterations, precisionThreshold, vertices, nodeTypes, parents, nodeWeights, edgeWeights, childrenList) {
    .Call(`_tgcc_updateUSC`, dataMatrix, initialMatrix, lambda, gamma, maxIterations, precisionThreshold, vertices, nodeTypes, parents, nodeWeights, edgeWeights, childrenList)
}

updateUBC <- function(dataMatrix, initialMatrix, lambda, gamma, maxIterations, precisionThreshold, verticesSamples, typesSamples, parentsSamples, nodeWeightsSamples, edgeWeightsSamples, childrenListSamples, verticesFeatures, typesFeatures, parentsFeatures, nodeWeightsFeatures, edgeWeightsFeatures, childrenListFeatures) {
    .Call(`_tgcc_updateUBC`, dataMatrix, initialMatrix, lambda, gamma, maxIterations, precisionThreshold, verticesSamples, typesSamples, parentsSamples, nodeWeightsSamples, edgeWeightsSamples, childrenListSamples, verticesFeatures, typesFeatures, parentsFeatures, nodeWeightsFeatures, edgeWeightsFeatures, childrenListFeatures)
}

computeTheta <- function(nodeValues, lambda, vertices, nodeTypes, parents, nodeWeights, edgeWeights, childrenList) {
    .Call(`_tgcc_computeTheta`, nodeValues, lambda, vertices, nodeTypes, parents, nodeWeights, edgeWeights, childrenList)
}

initPrepare <- function(from, to, dist, gamma) {
    .Call(`_tgcc_initPrepare`, from, to, dist, gamma)
}

updatenew <- function(Theta, input, vertices, types, parents, nodeWeights, edgeWeights, childrenList) {
    .Call(`_tgcc_updatenew`, Theta, input, vertices, types, parents, nodeWeights, edgeWeights, childrenList)
}

